### ISSUE TITLE
Change name?

### ISSUE THREAD

**Issue by epicfaace** [TheStanfordDaily/stanforddaily#1]
Maybe we can come up with a unique name for this instead of just "stanford-daily" so the repo is distinctive?

**Comment by hesyifei** [comment]
I feel like it's a good name since it's for both the website and the app and that's the main components of the Daily, though I'm open to any suggestions. 😂

**Comment by epicfaace** [comment]
Potentially`daily-webapp`? I think the spelling of `stanford-daily` just throws me off because usually we spell it `stanforddaily`
