### ISSUE TITLE
Create archives page

### ISSUE THREAD

**Issue by epicfaace** [TheStanfordDaily/stanforddaily#3]
Create:
- [x] Author pages
- [x] Category pages
- [ ] Tag pages
- [ ] Month / year / day pages

category: https://www.stanforddaily.com/category/news/
subcategory: https://www.stanforddaily.com/category/arts-life/culture/
sub-sub-category: https://www.stanforddaily.com/category/sports/winter-sports/mens-gymnastics/
etc.

https://www.stanforddaily.com/2019/
https://www.stanforddaily.com/2019/01/
https://www.stanforddaily.com/2019/01/01

**Comment by hesyifei** [comment]
See also https://spectrum.chat/next-js/general/matching-an-unlimited-number-of-paths-deep-with-dynamic-routing~df9863b3-5471-4a1e-806e-3ec88b6b7b1d.

So for category, we probably need to create `pages/[category-slug].tsx`,`pages/[sub-category]/[category-slug].tsx`, and `pages/[sub-category]/[subsub-category]/[category-slug].tsx` (or even more - check the deepest level of sub-category).
