### ISSUE TITLE
Add a donation box under each article

### ISSUE THREAD

**Issue by hesyifei** [TheStanfordDaily/stanforddaily#33]
Should use this component: https://github.com/TheStanfordDaily/stanforddaily/blob/b5f3aa0decb42c7eb818d2e3d3cd8c7e50092045/components/DonationForm.tsx

Helpful reference: https://github.com/TheStanfordDaily/stanforddaily/blob/b5f3aa0decb42c7eb818d2e3d3cd8c7e50092045/components/HeaderDonationBanner.tsx

**Comment by epicfaace** [comment]
We want it to look like this:

![image](https://user-images.githubusercontent.com/1689183/79076957-b380f600-7ccb-11ea-9598-b75f4769d9a2.png)
