### ISSUE TITLE
Do some kind of old->new URL testing

### ISSUE THREAD

**Issue by epicfaace** [TheStanfordDaily/stanforddaily#4]
Take a sample of different pages on old site & make sure the same paths aren't broken on the new site.

It might be good to do this before the site is deployed.

**Comment by hesyifei** [comment]
We can generate a list of most viewed URLs from Google Analytics and test them.

**Comment by epicfaace** [comment]
https://beta.stanforddaily.com/2019/09/24/we-have-her-back-students-hold-rally-in-solidarity-with-chanel-miller/ - good

https://beta.stanforddaily.com/category/data-vizzes/ - good

https://beta.stanforddaily.com/email-digests/ - need to remove author and date from pages ("Do-Hyoung Park")

https://beta.stanforddaily.com/advertise/ - need to fix this! (and other pages using the WPBakery page builder)

**Comment by hesyifei** [comment]
`ubergrids` etc. actually works. See https://beta.stanforddaily.com/join-the-daily
