### ISSUE TITLE
Clicking on "donate" gets the wrong link in paypal

### ISSUE THREAD

**Issue by epicfaace** [TheStanfordDaily/stanforddaily#6]
It gives us a wp-json link instead of the actual article link.

![image](https://user-images.githubusercontent.com/1689183/64915061-3e3c4b00-d713-11e9-952d-203b69901b73.png)

**Comment by hesyifei** [comment]
Fixed in the header with `DonationForm` component (https://github.com/TheStanfordDaily/stanforddaily/blob/b5f3aa0decb42c7eb818d2e3d3cd8c7e50092045/components/DonationForm.tsx). Should be fixed for the donation box under the article with #33.
